@echo off
setlocal enabledelayedexpansion
title ThumbsAI — Data Backup
color 0B

echo ================================================================================
echo   ThumbsAI — Data Backup
echo   Backs up: settings.json, thumbs.db
echo   Designed by: Zero  ^|  Built by: Jarvis
echo ================================================================================
echo.
echo   User data lives in the  data\  folder.
echo   This script creates a timestamped snapshot in  _backups\
echo.

set "DIR=%~dp0"
set "DATADIR=%DIR%data"
set "BACKUPROOT=%DIR%_backups"

:: ── Timestamp via PowerShell (locale-independent) ────────────────────────────
for /f %%T in ('powershell -NoProfile -Command "Get-Date -Format 'yyyy-MM-dd_HHmmss'"') do set "STAMP=%%T"
set "BACKUPDIR=!BACKUPROOT!\!STAMP!"

if not exist "!BACKUPROOT!" mkdir "!BACKUPROOT!"
mkdir "!BACKUPDIR!"

echo   Backup destination: !BACKUPDIR!
echo.

:: ── settings.json (always backs up — contains watched folders, favorites) ────
echo [1/2] Backing up settings.json...
if exist "%DATADIR%\settings.json" (
    copy /Y "%DATADIR%\settings.json" "!BACKUPDIR!\settings.json" >nul
    echo [OK] settings.json backed up.
    echo      (Contains: favorites, watched folders, launch apps, sort preferences)
) else (
    echo [SKIP] settings.json not found — app has not been run yet.
)

echo.

:: ── thumbs.db (optional — may be very large) ─────────────────────────────────
echo [2/2] thumbs.db (thumbnail cache database)...
if exist "%DATADIR%\thumbs.db" (
    for /f %%S in ('powershell -NoProfile -Command "[math]::Round((Get-Item '%DATADIR%\thumbs.db').Length/1GB, 2)"') do set "DBGB=%%S"
    echo      Current size: !DBGB! GB
    echo      NOTE: This can take several minutes to copy.
    echo.
    set /p "COPYDB=Back up thumbs.db? (Y/N): "
    if /i "!COPYDB!"=="Y" (
        echo [COPYING] Please wait...
        copy /Y "%DATADIR%\thumbs.db" "!BACKUPDIR!\thumbs.db" >nul
        if !errorlevel! EQU 0 (
            echo [OK] thumbs.db backed up.
        ) else (
            echo [ERROR] thumbs.db copy failed. Is the app still running?
        )
    ) else (
        echo [SKIP] thumbs.db skipped.
        echo        Thumbnails can be regenerated by re-scanning your folders.
    )
) else (
    echo [SKIP] thumbs.db not found.
)

echo.
echo ================================================================================
echo   Backup complete: !BACKUPDIR!
echo ================================================================================
echo.

set /p "OPEN=Open backup folder? (Y/N): "
if /i "!OPEN!"=="Y" explorer "!BACKUPDIR!"

pause
